[Models]
intern_path=../intern_fw_test/InternVL2_5-8B-MPO
ds_path=/nfs/stak/users/beerya/soundbendor/food_cap_datasets/FoodX-251
db_path=cn-m-1.hpc.engr.oregonstate.edu:6333
llm=gemma3:27b
# can either be a file path to a finetuned model or a model name
embed_model=all-mpnet-base-v2
dictionary=assets/descriptor_dictionary.json
collection_name=food_descriptor_gemma5

[Settings]
# either some integer or 'all' for entire subset
n_samples = 100


