[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "Intern-FW"
version = "0.0.1"

[project.scripts]
test_classification = "app:test_classification"
generate_descriptions = "app:generate_descriptions"
build_vdb = "app:build_vdb"
caption_imgs = "app:caption_imgs"
merge_captions = "app:merge_files"
convert_dict = "app:convert_csv_to_dictionary"

[tool.setuptools.packages.find]
where = ["src"]

