[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "Intern-FW"
version = "0.0.1"

[project.scripts]
eval_embed = "evaluate_embed:main"
build_descriptions = "build_descriptor:main"
build_vdb = "build_vdb:main"
caption_imgs = "caption_imgs:main"
merge_captions = "caption_imgs:merge_files"

[tool.setuptools.packages.find]
where = ["src"]

