[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "Intern-FW"
version = "0.0.1"

[project.scripts]
test_classification = "app:test_classification"
generate_descriptions = "app:generate_descriptions"
build_vdb = "app:build_vdb"
caption_imgs = "app:caption_imgs"
merge_captions = "app:merge_files"
convert_dict = "app:convert_csv_to_dictionary"
build_clip_db = "app:build_img_vdb"
test_clip = "app:eval_img_vdb"
test_yolo = "yolo:main"
seg_to_boxes = "util.seg_to_boxes:main"
yolo_world = "yolo_world:main"

[tool.setuptools.packages.find]
where = ["src"]

